### ISSUE TITLE
pairing challenges

### ISSUE THREAD

**Issue by stoeffel** [elm-zurich/meetup#2]
# Concept
- We group up in pairs.
- After each round we build new pairs.
- A round goes f.e. 15 minutes (time tbd).
- We work on the same problem in each round.
- Each round has new obstacles (f.e. you can not speak)
# Goal
- getting to know meetup members
- writing code in an unusual setup
- having fun
## Idea

I got this idea from a coworker, who was part of something similar at AndConf.
# Todo
- [ ] find a nice problem
- [ ] determine time for each round
- [ ] find obstacles

**Comment by stoeffel** [comment]
How would you feel about one round being "PureScript"?

**Comment by grossbart** [comment]
I like the idea of these challenges very much! @wereHamster could support us in the PureScript round :smile:

**Comment by stoeffel** [comment]
## some ideas for rounds
- only one person can see the code
- no talking
- only on paper
- TDD

**Comment by jwoudenberg** [comment]
I really like this concept. Finding a good problem is probably the tricky part, because it needs to be simple enough to be solvable in a short timespan but interesting enough to work on together. Perhaps some simple game we can make up you need to write an 'AI' for. Something simple enough to allow a simple solution in minutes, but with the possibility that each round you can try to create something a little better then the round before.

#### More ideas for rounds
- You are not allowed to run the program until finished (i.e. First attempt should work, perhaps not really a challenge in Elm...).
- You get the program by another couple from a previous round and need to improve it in some way without removing existing lines of code.
- Don't solve the problem but write a completely over engineered  solution to a tiny aspect of the problem.

**Comment by stoeffel** [comment]
:thought_balloon: I somehow would like the idea of creating something that plays music :smile: :notes:

**Comment by stoeffel** [comment]
How about creating a guitar hero like game?

**Comment by stoeffel** [comment]
ah, probably to hard. I think a game would be nice though. something like pong.

**Comment by jwoudenberg** [comment]
I think Pong is a very good idea. Another one I just thought of: Hangman. I think it might be interesting because it is simple but still consists of some even simpler parts which allow you to get some result even if you don't manage to complete the full challenge in a short timespan. For instance: different starting focuses could be the drawing of the figure, the entering and optional validation of word or the guessing of letters.

Regardless of what we pick (I still think making a decision this week is a good idea): If people run out of time, we can offer them to take some code with them to the next challenge (or start over, whatever people like best). That might be a better alternative than rushing people to complete the challenge each round. In particular in pairing where one person knows a lot more than the other, it would be nicer if they take their time and the person knowing more can tutor the other a bit.

**Comment by stoeffel** [comment]
How about we just decide for a challenge with the whole group? We let people vote for pong, hangman or something else?

> If people run out of time, we can offer them to take some code with them to the next challenge

SGTM

**Comment by jwoudenberg** [comment]
Perfect!

**Comment by stoeffel** [comment]
# Pairing Quest

## Intro
- what's the plan
  - rounds of 20min (maybe change it when we see that it's too long/short)
  - all work on the same problem
    - we vote for a problem (Pong, hangman, or other ideas from the attendees)
  - we swap pairs each round
  - each round presents us with a new challenge
- what's the goal of this
  - having fun with elm
  - getting to know everyone
  - learning new stuff

## Problem choices
- Pong
- Hangman ( <= is probably the best problem because it's the easiest)
- sudoku
- tetris
- 2048

## Rounds
1. nothing
2. You are not allowed to run the program until finished
3. overengineering on part of the problem
4. improve the solution of someone else (everyone should upload code to github)
5. use another language (PureScript, reason, clojurescript) would be cool to use something you don't know

**Comment by stoeffel** [comment]
My preference is:
1. 2048
2. tetris
3. sudoku
4. hangman
5. pong ( last, because it involves subscriptions, timing, keyboard, two players)

**Comment by stoeffel** [comment]
a stopwatch would also be a nice problem.

**Comment by stoeffel** [comment]
just thought of another nice problem. [mastermind](https://en.m.wikipedia.org/wiki/Mastermind_%28board_game%29)
- easy ui
- interesting problems
  - random
  - finding color/exactMatches

**Comment by jwoudenberg** [comment]
That's a really cool one!

I'm wondering what more we need to prepare for Friday.
- We probably need to do a short introduction talk to explain the idea. Would anyone like to do this? What points do we need to cover in this talk?
  - explain the concept
  - perhaps check everyone has a working Elm environment, otherwise give people some time to set theirs up?
- Do we need to project a clock somewhere central so everyone can easily see how much time is left? Or are we distributed in several rooms and is there no point in doing this?
- How do we create randomized couples? Create a small app? Consider the possibility some people might not have brought a laptop?
- Is everyone going to participate or are we going to keep some people aside as 'mentors'?

**Comment by jwoudenberg** [comment]
The more I think about mastermind, the more I like the idea. I'd say let's go for that!

**Comment by stoeffel** [comment]
I can do the intro!

> Do we need to project a clock somewhere central so everyone can easily see how much time is left?

I don't think so. We will just tell the time from time to time.

> How do we create randomized couples? Create a small app? Consider the possibility some people might not have brought a laptop?

I think we will just let people regroup on their own.

> Is everyone going to participate or are we going to keep some people aside as 'mentors'?

Not sure. I think we all should code though.

**Comment by jwoudenberg** [comment]
Sounds good to me!
